## nav
navbar:
  visiable: auto
  logo: 
    img: '' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
    icon:
    title: 'Nano' 
  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      url: friends/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/
## cover
cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: true
  title: 'Mlikiowa Home Village'
  subtitle: ''
  background: https://s2.loli.net/2022/08/09/Zh7waM9cmIPGe3k.jpg
  search: A Wonderful Theme for Hexo # search
  features:
    - name: 博客
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg
      url: /
    - name: 分类
      img: volantis-static/media/twemoji/assets/svg/1f516.svg
      url: /categories/
      target: _self
    - name: 标签
      img: volantis-static/media/twemoji/assets/svg/1f4af.svg
      url: /tags/
    - name: 归档
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg
      url: /archives/  
    - name: 友链
      img: volantis-static/media/twemoji/assets/svg/1f497.svg
      url: /friends/  
    - name: 关于
      img: volantis-static/media/twemoji/assets/svg/1f4ac.svg
      url: /about/
## comments
comments:
  service: giscus
  giscus:
    repo: Mlikiowa/MliKiowa.github.io
    repo-id: R_kgDOHxvLiA
    category: General
    category-id: DIC_kwDOHxvLiM4CQr9N
    mapping: "url"
    reactions-enabled: "1"
    emit-metadata: "0"
    lang: "zh-CN"
    theme:
      light: "light" # https://fastly.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
      dark: "dark" # https://fastly.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css
## Friend
## article
article:
  preview:
    scheme: landscape # landscape  
    pin_icon: https://fastly.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: false # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    top_meta: [author, category, date, wordcount] #启用评论数量需在此添加       
    bottom_meta: [updated, tags]
    footer_widget:
      references:
        icon: fa-light fa-quote-left CONCRETE
      copyright:
        enable: true
        content:
          - '博客内容遵循 <a href="/page/cc">署名-非商业性使用-相同方式共享 4.0 国际</a> 协议。'
        custom: true # 开启后替代上方内容的版权显示                     
    meta_library:   
      author:
        avatar: https://q1.qlogo.cn/g?b=qq&nk=1627126029&s=100
        name: Mlikiowa
        url: /
      date:
        icon: fas fa-calendar-alt
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      category:
        icon: fas fa-folder-open      
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag  
site_footer:
  layout: [copyright]
  copyright: '⌘ Hexo With Volantis'  
custom_css:
  cursor:
    enable: true
  font_smoothing: true
  # sidebar:
  #   effect: [shadow] # [shadow, floatable, blur]
  # body:
  #   effect: [shadow] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'Sotheby'
      name: 'Sotheby'
      url: https://nanaeo.cn/asset/Sotheby.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/moieo/moieo@main/moieo.woff2
      weight: normal
      style: normal
## sidebar
sidebar:
  position: right # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, webinfo]
  for_post: [toc]
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://q1.qlogo.cn/g?b=qq&nk=1627126029&s=100
      shape: circle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fa-solid fa-rss
          url: /atom.xml
        - icon: fa-solid fa-envelope
          url: mailto:me@xxx.com
        - icon: fab fa-github
          url: https://github.com/volantis-x/
        - icon: fa-solid fa-headphones-alt
          url: /
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      sticky: true
      header:
        icon: fa-solid fa-list
        title: Content
      list_number: false
      min_depth: 2
      max_depth: 5
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: /blog/categories/
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: false
          data: '2022/08/05'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          siteuv:
            enable: false
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: false
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    # ---------------------------------------
    # lastupdate widget
    lastupdate:
      class: lastupdate
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-clock WISTERIA
        title: 最近更新
plugins:
  wordcount:
    enable: true
  pjax:
    enable: true
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#ffcccc'
    # 链接色
    link: '#ec7bb6'
    # 按钮色
    button: '#f3c5ce'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#d9d3f6, 0.5)'
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: '#e0eeee'
    # 网站背景上的文字
    site_inner: '#fff'
    # 网站页脚文字
    site_footer: '#666'

    # 卡片背景色
    card: '#fff0f5'
    # 卡片上的普通文字
    text: '#eea9b8'

    # 区块和代码块背景色
    block: '#f6f6f6'
    # 代码块高亮时的背景色
    codeblock: '#e0eeee'
    # 行内代码颜色
    inlinecode: '#ec7bb6'
    # 文章部分
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#23464f'
    h4: '#23464f'
    h5: '#23464f'
    h6: '#23464f'
    p: '#23464f'

    # 列表文字
    list: '#eea9b8'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #d9d3f6, 80)'
    # 辅助性文字
    meta: '#888'
    
    # 版权卡片背景色
    copyright_bkg: '#f5f5f5'
  # ------------
  # 暗色主题
  # https://www.maijisheji.com/2094.html
  dark:
    # 网站最深底色            # Dark Grey 1
    site_bd: '#121212'
    # 网站背景色              # Dark Grey 2
    site_bg: '#1f1f1f'
    # 卡片背景色              # Dark Grey 3
    card: '#262626'
    # 网站背景上的文字
    site_inner: '#eeeeeede'
    # 网站页脚文字
    site_footer: '#aaaaaade'
    # 卡片上的普通文字
    text: '#eeeeeede'

    # 区块和代码块背景色       # Dark Grey 4
    block: '#434343'
    # 代码块高亮时的背景色     # Dark Grey 2
    codeblock: '#1f1f1f'
    # 行内代码颜色
    inlinecode: '#D56D28'

    # 文章部分 高强度文本的不透明度应为87％ 中等重点文字适用于60％
    h1: '#FFFFFFde'            #  Dark Grey 8
    h2: '#FFFFFFde'
    h3: '#FFFFFF99'            #  Dark Grey 7
    h4: '#FFFFFF99'
    h5: '#FFFFFF99'
    h6: '#FFFFFF99'
    p: '#ffcccc'           #  Dark Grey 6

    # 列表文字                #  Dark Grey 6
    list: '#d9d9d9de'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #fff, 80)'
    # 辅助性文字              #  Dark Grey 5
    meta: '#bfbfbfde'
    # 版权卡片背景色
    copyright_bkg: '#21252b'
    # 夜间图片亮度
    brightness: 70%
## cdn_version: false
content_visibility: true
