name: Deploy Hexo
on:
  repository_dispatch:
    types:
      - FriendGenerate
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Setup Hexo Blog Dependencies
        run: bash ./script/Dependent.sh
      - name: Hexo Blog Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: bash ./script/Deploy.sh    
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Generate Public Files
        run: |
          # Restore last modified time
          git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done