name: Deploy Hexo
on:
  repository_dispatch:
    types:
      - FriendGenerate
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
